# Generated by Django 4.1.1 on 2022-09-30 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidoP', models.CharField(max_length=70)),
                ('apellidoM', models.CharField(max_length=70)),
                ('numCelular', models.CharField(max_length=20)),
                ('correoElectronico', models.CharField(max_length=200)),
                ('carrera', models.CharField(choices=[('Sistemas', 'Ingenieria Sistemas Computacionales'), ('Civil', 'Ingenieria Civil'), ('Industrial', 'Ingenieria Industrial')], max_length=200)),
                ('semestre', models.IntegerField(choices=[('8', 8), ('9', 9), ('10', 10), ('11', 11), ('12', 12), ('13', 13), ('14', 14)])),
                ('institutoSeguridadSocial', models.CharField(max_length=200)),
                ('fotoUsuario', models.ImageField(blank=True, default='images/profile.png', null=True, upload_to='profilesPic/')),
            ],
        ),
    ]
