# Generated by Django 4.1.1 on 2022-09-30 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='carrera',
            field=models.CharField(choices=[('Sistemas', 'Ingenieria Sistemas Computacionales'), ('Civil', 'Ingenieria Civil'), ('Industrial', 'Ingenieria Industrial')], default='Ingenieria Sistemas Computacionales', max_length=200),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='semestre',
            field=models.IntegerField(choices=[(8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14')]),
        ),
    ]
