# Generated by Django 4.1.1 on 2022-10-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_alter_estudiante_carrera_alter_estudiante_semestre'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='numControl',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='numSeguridadSocial',
            field=models.CharField(blank=True, max_length=70, null=True, unique=True),
        ),
    ]
