# Generated by Django 4.1.1 on 2022-10-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_estudiante_numcontrol_estudiante_numseguridadsocial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='numControl',
            field=models.CharField(default='12345678', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='numSeguridadSocial',
            field=models.CharField(default='##########', max_length=70, unique=True),
        ),
    ]
