# Generated by Django 4.1.1 on 2022-10-03 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Accounts', '0006_domicilio_estudiante_domicilio'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='estado',
            field=models.CharField(choices=[('Aguascalientes', 'Aguascalientes'), ('Baja California', 'Baja California'), ('Baja California Sur', 'Baja California Sur'), ('Campeche', 'Campeche'), ('Chiapas', 'Chiapas'), ('Chihuahua', 'Chihuahua'), ('Coahuila', 'Coahuila'), ('Colima', 'Colima'), ('Ciudad de México', 'Ciudad de México'), ('Durango', 'Durango'), ('Guanajuato', 'Guanajuato'), ('Guerrero', 'Guerrero'), ('Hidalgo', 'Hidalgo'), ('Jalisco', 'Jalisco'), ('Estado de Mexico', 'Estado de Mexico'), ('Michoacan', 'Michoacan'), ('Morelos', 'Michoacan'), ('Nayarit', 'Nayarit'), ('Nuevo Leon', 'Nuevo Leon'), ('Oaxaca', 'Oaxaca'), ('Puebla', 'Puebla'), ('Queretaro', 'Queretaro'), ('Quintana Roo', 'Quintana Roo'), ('San Luis Potosi', 'San Luis Potosi'), ('Sinaloa', 'Sinaloa'), ('Sonora', 'Sonora'), ('Tabasco', 'Tabasco'), ('Tamaulipas', 'Tamaulipas'), ('Tlaxcala', 'Tlaxcala'), ('Veracruz', 'Veracruz'), ('Yucatan', 'Yucatan'), ('Zacatecas', 'Zacatecas')], default='Oaxaca', max_length=20),
        ),
    ]
