# Generated by Django 4.1.1 on 2022-10-04 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0007_estudiante_user_alter_domicilio_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus', models.CharField(max_length=15)),
                ('calificacion', models.IntegerField()),
                ('reporteDoc', models.FileField(blank=True, null=True, upload_to='reports/')),
            ],
        ),
        migrations.CreateModel(
            name='ReporteParcial1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus', models.CharField(max_length=15)),
                ('calificacion', models.IntegerField()),
                ('reporteDoc', models.FileField(blank=True, null=True, upload_to='reports/')),
            ],
        ),
        migrations.CreateModel(
            name='ReporteParcial2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus', models.CharField(max_length=15)),
                ('calificacion', models.IntegerField()),
                ('reporteDoc', models.FileField(blank=True, null=True, upload_to='reports/')),
            ],
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='domicilio',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Accounts.domicilio'),
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartaPresentacion', models.FileField(blank=True, null=True, upload_to='records/')),
                ('cartaCompromiso', models.FileField(blank=True, null=True, upload_to='records/')),
                ('cronograma', models.FileField(blank=True, null=True, upload_to='records/')),
                ('residenciaDoc', models.FileField(blank=True, null=True, upload_to='records/')),
                ('manuaDoc', models.FileField(blank=True, null=True, upload_to='records/')),
                ('reporteFinal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Accounts.reportefinal')),
                ('reporteParcial1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Accounts.reporteparcial1')),
                ('reporteParcial2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Accounts.reporteparcial2')),
            ],
        ),
        migrations.AddField(
            model_name='estudiante',
            name='expediente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Accounts.expediente'),
        ),
    ]
