# Generated by Django 4.1.1 on 2022-10-04 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0009_alter_estudiante_expediente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expediente',
            name='reporteFinal',
        ),
        migrations.RemoveField(
            model_name='expediente',
            name='reporteParcial1',
        ),
        migrations.RemoveField(
            model_name='expediente',
            name='reporteParcial2',
        ),
    ]
