# Generated by Django 4.1.1 on 2022-10-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0010_remove_expediente_reportefinal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='curp',
            field=models.CharField(max_length=18, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='fotoUsuario',
            field=models.ImageField(blank=True, default='images/profilepic.png', null=True, upload_to='profilesPic/'),
        ),
    ]
