# Generated by Django 4.1.1 on 2022-10-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0011_estudiante_curp_alter_estudiante_fotousuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='domicilio',
            name='municipio',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='calle',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='codigoPostal',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='colonia',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
