# Generated by Django 4.1.1 on 2022-10-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0012_domicilio_municipio_alter_domicilio_calle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='carrera',
            field=models.CharField(choices=[('Ingenieria Sistemas Computacionales', 'Ingenieria Sistemas Computacionales'), ('Ingenieria Civil', 'Ingenieria Civil'), ('Ingenieria Industrial', 'Ingenieria Industrial')], default='Ingenieria Sistemas Computacionales', max_length=200),
        ),
    ]
