# Generated by Django 4.1.1 on 2022-10-05 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0017_alter_estudiante_institutoseguridadsocial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='domicilio',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.domicilio'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='expediente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.expediente'),
        ),
    ]
