# Generated by Django 4.1.1 on 2022-10-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0019_alter_estudiante_fotousuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='numSeguridadSocial',
            field=models.CharField(max_length=70, null=True, unique=True),
        ),
    ]
