# Generated by Django 4.1.1 on 2022-10-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0020_alter_estudiante_numseguridadsocial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='numSeguridadSocial',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
