# Generated by Django 4.1.1 on 2022-10-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0022_alter_domicilio_calle_alter_domicilio_codigopostal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='curp',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
    ]
