# Generated by Django 4.1.1 on 2022-10-06 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0023_alter_estudiante_curp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='expediente',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.expediente'),
        ),
    ]
