# Generated by Django 4.1.1 on 2022-10-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0024_alter_estudiante_expediente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expediente',
            name='manuaDoc',
        ),
        migrations.AddField(
            model_name='expediente',
            name='manualDoc',
            field=models.FileField(blank=True, null=True, upload_to='records/manual'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='cartaCompromiso',
            field=models.FileField(blank=True, null=True, upload_to='records/cartaC/'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='cartaPresentacion',
            field=models.FileField(blank=True, null=True, upload_to='records/cartaP/'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='cronograma',
            field=models.FileField(blank=True, null=True, upload_to='records/crono/'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='residenciaDoc',
            field=models.FileField(blank=True, null=True, upload_to='records/resiDoc/'),
        ),
    ]
