# Generated by Django 4.1.1 on 2022-10-06 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0026_expediente_reportefinal_expediente_reporteparcial1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='manualDoc',
            field=models.FileField(blank=True, null=True, upload_to='records/manual/'),
        ),
        migrations.AlterField(
            model_name='reportefinal',
            name='calificacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportefinal',
            name='estatus',
            field=models.CharField(choices=[('ENVIADO', 'ENVIADO'), ('PENDIENTE', 'PENDIENTE'), ('REVISADO', 'REVISADO'), ('ACEPTADO', 'ACEPTADO'), ('RECHAZADO', 'RECHAZADO')], default='ENVIADO', max_length=15),
        ),
        migrations.AlterField(
            model_name='reportefinal',
            name='reporteDoc',
            field=models.FileField(blank=True, null=True, upload_to='records/reporteF/'),
        ),
        migrations.AlterField(
            model_name='reporteparcial1',
            name='calificacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reporteparcial1',
            name='estatus',
            field=models.CharField(choices=[('ENVIADO', 'ENVIADO'), ('PENDIENTE', 'PENDIENTE'), ('REVISADO', 'REVISADO'), ('ACEPTADO', 'ACEPTADO'), ('RECHAZADO', 'RECHAZADO')], default='ENVIADO', max_length=15),
        ),
        migrations.AlterField(
            model_name='reporteparcial1',
            name='reporteDoc',
            field=models.FileField(blank=True, null=True, upload_to='records/reporte1/'),
        ),
        migrations.AlterField(
            model_name='reporteparcial2',
            name='calificacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reporteparcial2',
            name='estatus',
            field=models.CharField(choices=[('ENVIADO', 'ENVIADO'), ('PENDIENTE', 'PENDIENTE'), ('REVISADO', 'REVISADO'), ('ACEPTADO', 'ACEPTADO'), ('RECHAZADO', 'RECHAZADO')], default='ENVIADO', max_length=15),
        ),
        migrations.AlterField(
            model_name='reporteparcial2',
            name='reporteDoc',
            field=models.FileField(blank=True, null=True, upload_to='records/reporte2/'),
        ),
    ]
