# Generated by Django 4.1.1 on 2022-10-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0029_alter_reportefinal_estatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportefinal',
            name='reporteDoc',
            field=models.FileField(upload_to='records/reporteF/'),
        ),
        migrations.AlterField(
            model_name='reporteparcial1',
            name='reporteDoc',
            field=models.FileField(upload_to='records/reporte1/'),
        ),
        migrations.AlterField(
            model_name='reporteparcial2',
            name='reporteDoc',
            field=models.FileField(upload_to='records/reporte2/'),
        ),
    ]
