# Generated by Django 4.1.1 on 2022-10-11 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0030_alter_reportefinal_reportedoc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportefinal',
            old_name='reporteDoc',
            new_name='reporteDocFinal',
        ),
    ]
