# Generated by Django 4.1.1 on 2022-10-12 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0031_rename_reportedoc_reportefinal_reportedocfinal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reporteparcial1',
            old_name='reporteDoc',
            new_name='reporte1Doc',
        ),
        migrations.RenameField(
            model_name='reporteparcial2',
            old_name='reporteDoc',
            new_name='reporte2Doc',
        ),
    ]
