# Generated by Django 4.1.1 on 2022-10-12 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Accounts', '0032_rename_reportedoc_reporteparcial1_reporte1doc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='fotoUsuario',
            field=models.ImageField(blank=True, default='profilepic.png', null=True, upload_to='profilesPic/students/'),
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidoP', models.CharField(max_length=70)),
                ('apellidoM', models.CharField(max_length=70)),
                ('numCelular', models.CharField(max_length=20)),
                ('correoElectronico', models.CharField(blank=True, max_length=200, null=True)),
                ('curp', models.CharField(blank=True, max_length=18, null=True)),
                ('rfc', models.CharField(blank=True, max_length=13, null=True)),
                ('estatus', models.CharField(blank=True, choices=[('ACTIVO', 'ACTIVO'), ('VACACIONES', 'VACIONES'), ('INACTIVO', 'INACTIVO')], default='ACTIVO', max_length=15)),
                ('fotoUsuario', models.ImageField(blank=True, default='profilepic.png', null=True, upload_to='profilesPic/teachers/')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
