# Generated by Django 4.1.1 on 2022-10-12 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0033_alter_estudiante_fotousuario_docente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='numControl',
            field=models.CharField(blank=True, error_messages={'unique': 'Existe otro alumno con este numero de control.'}, max_length=8, unique=True),
        ),
        migrations.CreateModel(
            name='Anteproyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('tipoProyecto', models.CharField(choices=[('PROPUESTA PROPIA', 'PROPUESTA PROPIA'), ('BANCO DE PROYECTOS', 'BANCO DE PROYECTOS')], default='ACTIVO', max_length=25)),
                ('fechaEntrega', models.DateTimeField()),
                ('numIntegrantes', models.IntegerField()),
                ('estatus', models.CharField(blank=True, choices=[('ENVIADO', 'ENVIADO'), ('PENDIENTE', 'PENDIENTE'), ('REVISADO', 'REVISADO'), ('ACEPTADO', 'ACEPTADO'), ('RECHAZADO', 'RECHAZADO')], default='ENVIADO', max_length=15)),
                ('codigoUnion', models.CharField(max_length=10)),
                ('observaciones', models.CharField(blank=True, max_length=500, null=True)),
                ('docente', models.ManyToManyField(blank=True, null=True, to='Accounts.docente')),
            ],
        ),
    ]
