# Generated by Django 4.1.1 on 2022-10-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0034_alter_estudiante_numcontrol_anteproyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anteproyecto',
            name='docente',
            field=models.ManyToManyField(blank=True, to='Accounts.docente'),
        ),
    ]
