# Generated by Django 4.1.1 on 2022-10-12 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0035_alter_anteproyecto_docente'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='anteproyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.anteproyecto'),
        ),
    ]
