# Generated by Django 4.1.1 on 2022-10-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0036_estudiante_anteproyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anteproyecto',
            name='fechaEntrega',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
