# Generated by Django 4.1.1 on 2022-10-12 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0037_alter_anteproyecto_fechaentrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anteproyecto',
            name='codigoUnion',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
