# Generated by Django 4.1.1 on 2022-10-13 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0038_alter_anteproyecto_codigounion'),
    ]

    operations = [
        migrations.AddField(
            model_name='anteproyecto',
            name='periodo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
