# Generated by Django 4.1.1 on 2022-10-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0039_anteproyecto_periodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='anteproyecto',
            field=models.FileField(blank=True, null=True, upload_to='records/anteproyecto/'),
        ),
    ]
