# Generated by Django 4.1.1 on 2022-10-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0040_expediente_anteproyecto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='anteproyecto',
        ),
        migrations.AddField(
            model_name='anteproyecto',
            name='estudiante',
            field=models.ManyToManyField(blank=True, to='Accounts.estudiante'),
        ),
    ]
