# Generated by Django 4.1.1 on 2022-10-13 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0041_remove_estudiante_anteproyecto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anteproyecto',
            old_name='docente',
            new_name='docentes',
        ),
        migrations.RemoveField(
            model_name='anteproyecto',
            name='estudiante',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='anteproyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.anteproyecto'),
        ),
    ]
