# Generated by Django 4.1.1 on 2022-10-13 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0042_rename_docente_anteproyecto_docentes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='numCelular',
            field=models.CharField(max_length=10),
        ),
    ]
