# Generated by Django 4.1.1 on 2023-02-26 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0045_anteproyecto_descripcion_alter_docente_estatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anteproyecto',
            name='descripcion',
            field=models.CharField(max_length=500),
        ),
    ]
