# Generated by Django 4.1.1 on 2022-10-14 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0046_titulardependencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dependencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rfc', models.CharField(blank=True, max_length=13, null=True)),
                ('giro', models.CharField(blank=True, choices=[('INDUSTRIAL', 'INDUSTRIAL'), ('SERVICIOS', 'SERVICIOS'), ('PUBLICO', 'PUBLICO'), ('PRIVADO', 'PRIVADO'), ('OTRO', 'OTRO')], default='PUBLICO', max_length=20)),
                ('numCelular', models.CharField(max_length=20)),
                ('correoElectronico', models.CharField(blank=True, max_length=200, null=True)),
                ('mision', models.CharField(max_length=200)),
                ('domicilio', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.domicilio')),
                ('titular', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.titulardependencia')),
            ],
        ),
    ]
