# Generated by Django 4.1.1 on 2023-02-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0046_alter_anteproyecto_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anteproyecto',
            name='descripcion',
            field=models.CharField(default='None', max_length=500),
        ),
    ]
