# Generated by Django 4.1.1 on 2022-10-14 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0047_dependencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='anteproyecto',
            name='dependencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Accounts.dependencia'),
        ),
    ]
