# Generated by Django 4.1.1 on 2023-02-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0047_alter_anteproyecto_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anteproyecto',
            name='descripcion',
            field=models.CharField(max_length=500),
        ),
    ]
