# Generated by Django 4.1.1 on 2022-10-14 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0048_anteproyecto_dependencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsesorExterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidoP', models.CharField(max_length=70)),
                ('apellidoM', models.CharField(max_length=70)),
                ('puesto', models.CharField(max_length=50)),
                ('dependencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Accounts.dependencia')),
            ],
        ),
    ]
