# Generated by Django 4.1.1 on 2023-03-28 15:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0049_alter_anteproyecto_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='anteproyecto',
            name='etiquetas',
            field=models.ManyToManyField(blank=True, to='Accounts.etiqueta'),
        ),
    ]
