# Generated by Django 4.1.1 on 2022-10-14 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0049_asesorexterno'),
    ]

    operations = [
        migrations.AddField(
            model_name='anteproyecto',
            name='asesorExterno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Accounts.asesorexterno'),
        ),
        migrations.AlterField(
            model_name='anteproyecto',
            name='docentes',
            field=models.ManyToManyField(blank=True, null=True, to='Accounts.docente'),
        ),
    ]
