# Generated by Django 4.1.1 on 2022-10-14 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0050_anteproyecto_asesorexterno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anteproyecto',
            name='docentes',
            field=models.ManyToManyField(blank=True, to='Accounts.docente'),
        ),
    ]
