# Generated by Django 4.1.1 on 2023-03-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0050_etiqueta_anteproyecto_etiquetas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etiqueta',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
