# Generated by Django 4.1.1 on 2022-10-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0051_alter_anteproyecto_docentes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anteproyecto',
            name='periodo',
        ),
        migrations.AddField(
            model_name='anteproyecto',
            name='periodoFin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anteproyecto',
            name='periodoInicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
