# Generated by Django 4.1.1 on 2022-10-17 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0052_remove_anteproyecto_periodo_anteproyecto_periodofin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anteproyecto',
            name='numIntegrantes',
            field=models.IntegerField(default=1),
        ),
    ]
