# Generated by Django 4.1.1 on 2022-10-17 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0054_alter_anteproyecto_periodofin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='domicilio',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.domicilio'),
        ),
    ]
