# Generated by Django 4.1.1 on 2022-10-17 15:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0055_alter_estudiante_domicilio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anteproyecto',
            name='periodoInicio',
            field=models.DateField(default=datetime.date.today, null=True, verbose_name=('%d/%m/%Y',)),
        ),
    ]
