# Generated by Django 4.1.1 on 2022-10-17 15:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0056_alter_anteproyecto_periodoinicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anteproyecto',
            name='periodoInicio',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
