# Generated by Django 4.1.1 on 2022-10-17 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0057_alter_anteproyecto_periodoinicio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='titulardependencia',
            old_name='apellidoM',
            new_name='t_apellidoM',
        ),
        migrations.RenameField(
            model_name='titulardependencia',
            old_name='apellidoP',
            new_name='t_apellidoP',
        ),
        migrations.RenameField(
            model_name='titulardependencia',
            old_name='nombre',
            new_name='t_nombre',
        ),
        migrations.RenameField(
            model_name='titulardependencia',
            old_name='puesto',
            new_name='t_puesto',
        ),
    ]
