# Generated by Django 4.1.1 on 2022-10-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0059_rename_nombre_anteproyecto_a_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expediente',
            name='manualDoc',
        ),
        migrations.RemoveField(
            model_name='expediente',
            name='residenciaDoc',
        ),
        migrations.AddField(
            model_name='expediente',
            name='actaCalificaciones',
            field=models.FileField(blank=True, null=True, upload_to='records/actaCalificaciones/'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='actaResidencia',
            field=models.FileField(blank=True, null=True, upload_to='records/actaResidencia/'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='cartaAceptacion',
            field=models.FileField(blank=True, null=True, upload_to='records/cartaAceptacion/'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='cartaTerminacion',
            field=models.FileField(blank=True, null=True, upload_to='records/cartaTerminacion/'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='constanciaTerminacion',
            field=models.FileField(blank=True, null=True, upload_to='records/constanciaTerminacion/'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='dictamen',
            field=models.FileField(blank=True, null=True, upload_to='records/dictamen/'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='horario',
            field=models.FileField(blank=True, null=True, upload_to='records/horario/'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='solicitudResidencia',
            field=models.FileField(blank=True, null=True, upload_to='records/solicitudResidencia/'),
        ),
    ]
