# Generated by Django 4.1.1 on 2022-10-18 16:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0060_remove_expediente_manualdoc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportefinal',
            name='estatus',
        ),
        migrations.RemoveField(
            model_name='reportefinal',
            name='reporteDocFinal',
        ),
        migrations.RemoveField(
            model_name='reporteparcial1',
            name='calificacion',
        ),
        migrations.RemoveField(
            model_name='reporteparcial1',
            name='estatus',
        ),
        migrations.RemoveField(
            model_name='reporteparcial1',
            name='reporte1Doc',
        ),
        migrations.RemoveField(
            model_name='reporteparcial2',
            name='calificacion',
        ),
        migrations.RemoveField(
            model_name='reporteparcial2',
            name='estatus',
        ),
        migrations.RemoveField(
            model_name='reporteparcial2',
            name='reporte2Doc',
        ),
        migrations.AddField(
            model_name='reportefinal',
            name='rf_fechaEntrega',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='reportefinal',
            name='rf_formatoEvaluacion',
            field=models.FileField(blank=True, null=True, upload_to='records/reporteF/formatoEvaluacion/'),
        ),
        migrations.AddField(
            model_name='reportefinal',
            name='rf_hojaRevisores',
            field=models.FileField(blank=True, null=True, upload_to='records/reporteF/hojaRevisores/'),
        ),
        migrations.AddField(
            model_name='reporteparcial1',
            name='r1_fechaEntrega',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='reporteparcial1',
            name='r1_formatoEvaluacion',
            field=models.FileField(blank=True, null=True, upload_to='records/reporte1/formatoEvaluacion/'),
        ),
        migrations.AddField(
            model_name='reporteparcial1',
            name='r1_hojaRevisores',
            field=models.FileField(blank=True, null=True, upload_to='records/reporte1/hojaRevisores/'),
        ),
        migrations.AddField(
            model_name='reporteparcial2',
            name='r2_fechaEntrega',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='reporteparcial2',
            name='r2_formatoEvaluacion',
            field=models.FileField(blank=True, null=True, upload_to='records/reporte2/formatoEvaluacion/'),
        ),
        migrations.AddField(
            model_name='reporteparcial2',
            name='r2_hojaRevisores',
            field=models.FileField(blank=True, null=True, upload_to='records/reporte2/hojaRevisores/'),
        ),
    ]
