# Generated by Django 4.1.1 on 2022-10-25 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0061_remove_reportefinal_estatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anteproyecto',
            name='tipoProyecto',
            field=models.CharField(choices=[('PROPUESTA PROPIA', 'PROPUESTA PROPIA'), ('BANCO DE PROYECTOS', 'BANCO DE PROYECTOS'), ('TRABAJADOR', 'TRABAJADOR')], default='PROPUESTA PROPIA', max_length=25),
        ),
        migrations.CreateModel(
            name='Residencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('tipoProyecto', models.CharField(choices=[('PROPUESTA PROPIA', 'PROPUESTA PROPIA'), ('BANCO DE PROYECTOS', 'BANCO DE PROYECTOS'), ('TRABAJADOR', 'TRABAJADOR')], max_length=25)),
                ('numIntegrantes', models.IntegerField(default=1)),
                ('estatus', models.CharField(blank=True, choices=[('EN PROCESO', 'EN PROCESO'), ('PROROGA', 'PROROGA'), ('NO FINALIZADA', 'NO FINALIZADA'), ('RECHAZADA', 'RECHAZADA'), ('FINALIZADA', 'FINALIZADA')], default='EN PROCESO', max_length=15)),
                ('periodoInicio', models.DateField(null=True)),
                ('periodoFin', models.DateField(null=True)),
                ('observaciones', models.CharField(blank=True, max_length=500, null=True)),
                ('asesorExterno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Accounts.asesorexterno')),
                ('dependencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Accounts.dependencia')),
            ],
        ),
    ]
