# Generated by Django 4.1.1 on 2022-10-25 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0062_alter_anteproyecto_tipoproyecto_residencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='residencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.residencia'),
        ),
    ]
