# Generated by Django 4.1.1 on 2022-10-25 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0063_estudiante_residencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anteproyecto',
            name='observaciones',
        ),
    ]
