# Generated by Django 4.1.1 on 2022-10-25 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0065_observacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='anteproyecto',
            name='anteproyectoDoc',
            field=models.FileField(blank=True, null=True, upload_to='records/anteproyectoDoc/'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='anteproyecto',
            field=models.FileField(blank=True, null=True, upload_to='records/anteproyectoAceptado/'),
        ),
    ]
