# Generated by Django 4.1.1 on 2022-10-26 16:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0067_remove_expediente_actacalificaciones_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observacion',
            name='anteproyecto',
        ),
        migrations.RemoveField(
            model_name='observacion',
            name='docente',
        ),
        migrations.RemoveField(
            model_name='observacion',
            name='fechaObservacion',
        ),
        migrations.RemoveField(
            model_name='observacion',
            name='observacion',
        ),
        migrations.RemoveField(
            model_name='observacion',
            name='tiempoCorreccion',
        ),
        migrations.AddField(
            model_name='anteproyecto',
            name='observacion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Accounts.observacion'),
        ),
        migrations.AddField(
            model_name='observacion',
            name='fechaCreacion',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.CreateModel(
            name='ObservacionRevisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacionR', models.CharField(blank=True, max_length=255, null=True)),
                ('fechaElaboracionR', models.DateField(default=datetime.date.today)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.docente')),
            ],
        ),
        migrations.CreateModel(
            name='ObservacionAsesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agregarDias', models.PositiveIntegerField(default=0)),
                ('observacionA', models.CharField(blank=True, max_length=255, null=True)),
                ('fechaElaboracionA', models.DateField(default=datetime.date.today)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.docente')),
            ],
        ),
        migrations.AddField(
            model_name='observacion',
            name='observacionAsesor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.observacionasesor'),
        ),
        migrations.AddField(
            model_name='observacion',
            name='observacionRevisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.observacionrevisor'),
        ),
    ]
