# Generated by Django 4.1.1 on 2022-10-26 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0068_remove_observacion_anteproyecto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anteproyecto',
            name='docentes',
        ),
        migrations.AddField(
            model_name='anteproyecto',
            name='asesorInterno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asesorInterno', to='Accounts.docente'),
        ),
        migrations.AddField(
            model_name='anteproyecto',
            name='revisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisor', to='Accounts.docente'),
        ),
    ]
