# Generated by Django 4.1.1 on 2022-10-26 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0069_remove_anteproyecto_docentes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observacion',
            name='observacionAsesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.observacionasesor'),
        ),
        migrations.AlterField(
            model_name='observacion',
            name='observacionRevisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.observacionrevisor'),
        ),
    ]
