# Generated by Django 4.1.1 on 2022-10-27 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0070_alter_observacion_observacionasesor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observacion',
            name='observacionAsesor',
        ),
        migrations.RemoveField(
            model_name='observacion',
            name='observacionRevisor',
        ),
        migrations.AddField(
            model_name='observacionasesor',
            name='observacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.observacion'),
        ),
        migrations.AddField(
            model_name='observacionrevisor',
            name='observacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.observacion'),
        ),
        migrations.AlterField(
            model_name='observacionasesor',
            name='docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.docente'),
        ),
    ]
