# Generated by Django 4.1.1 on 2022-10-27 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0072_remove_observacionasesor_agregardias_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ObservacionAsesor',
            new_name='ObservacionDocente',
        ),
        migrations.RenameField(
            model_name='observaciondocente',
            old_name='observacionA',
            new_name='observacionD',
        ),
        migrations.DeleteModel(
            name='ObservacionRevisor',
        ),
    ]
