# Generated by Django 4.1.1 on 2022-10-27 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0073_rename_observacionasesor_observaciondocente_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observaciondocente',
            old_name='fechaElaboracionA',
            new_name='fechaElaboracion',
        ),
    ]
