# Generated by Django 4.1.1 on 2022-10-27 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0075_rename_agregardias_observacion_incrementardias'),
    ]

    operations = [
        migrations.AddField(
            model_name='residencia',
            name='r_asesorInterno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='r_asesorInterno', to='Accounts.docente'),
        ),
        migrations.AddField(
            model_name='residencia',
            name='r_revisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='r_revisor', to='Accounts.docente'),
        ),
    ]
