# Generated by Django 4.1.1 on 2022-10-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0076_residencia_r_asesorinterno_residencia_r_revisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='estatus',
            field=models.CharField(blank=True, choices=[('INICIAL', 'INICIAL'), ('PROCESO', 'PROCESO'), ('COMPLETO', 'COMPLETO')], default='ACTIVO', max_length=15),
        ),
    ]
