# Generated by Django 4.1.1 on 2022-10-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0077_expediente_estatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='estatus',
            field=models.CharField(blank=True, choices=[('INICIAL', 'INICIAL'), ('PROCESO', 'PROCESO'), ('COMPLETO', 'COMPLETO')], default='INICIAL', max_length=15),
        ),
    ]
