# Generated by Django 4.1.1 on 2022-11-01 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0080_alter_anteproyecto_estatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='anteproyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Accounts.anteproyecto'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='domicilio',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Accounts.domicilio'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='expediente',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Accounts.expediente'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='residencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Accounts.residencia'),
        ),
    ]
