# Generated by Django 4.1.1 on 2022-11-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0081_alter_estudiante_anteproyecto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residencia',
            name='observaciones',
        ),
        migrations.AlterField(
            model_name='residencia',
            name='estatus',
            field=models.CharField(blank=True, choices=[('INICIADA', 'INICIADA'), ('EN PROCESO', 'EN PROCESO'), ('PROROGA', 'PROROGA'), ('NO FINALIZADA', 'NO FINALIZADA'), ('RECHAZADA', 'RECHAZADA'), ('FINALIZADA', 'FINALIZADA')], default='INICIADA', max_length=15),
        ),
    ]
