# Generated by Django 4.1.1 on 2022-11-07 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0083_alter_dependencia_mision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anteproyecto',
            name='asesorInterno',
        ),
        migrations.RemoveField(
            model_name='anteproyecto',
            name='revisor',
        ),
        migrations.AddField(
            model_name='anteproyecto',
            name='revisor1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisor1', to='Accounts.docente'),
        ),
        migrations.AddField(
            model_name='anteproyecto',
            name='revisor2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisor2', to='Accounts.docente'),
        ),
    ]
