# Generated by Django 4.1.1 on 2022-11-09 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0084_remove_anteproyecto_asesorinterno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='puesto',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='docente',
            name='numCelular',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
