# Generated by Django 4.1.1 on 2022-11-14 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0085_docente_puesto_alter_docente_numcelular'),
    ]

    operations = [
        migrations.AddField(
            model_name='anteproyecto',
            name='estatusR1',
            field=models.CharField(blank=True, choices=[('PENDIENTE', 'PENDIENTE'), ('EN REVISION', 'EN REVISION'), ('ACEPTADO', 'ACEPTADO'), ('RECHAZADO', 'RECHAZADO')], default='EN REVISION', max_length=15),
        ),
        migrations.AddField(
            model_name='anteproyecto',
            name='estatusR2',
            field=models.CharField(blank=True, choices=[('PENDIENTE', 'PENDIENTE'), ('EN REVISION', 'EN REVISION'), ('ACEPTADO', 'ACEPTADO'), ('RECHAZADO', 'RECHAZADO')], default='EN REVISION', max_length=15),
        ),
        migrations.AlterField(
            model_name='anteproyecto',
            name='estatus',
            field=models.CharField(blank=True, choices=[('ENVIADO', 'ENVIADO'), ('PENDIENTE', 'PENDIENTE'), ('EN REVISION', 'EN REVISION'), ('REVISADO', 'REVISADO'), ('ACEPTADO', 'ACEPTADO'), ('RECHAZADO', 'RECHAZADO')], default='ENVIADO', max_length=15),
        ),
    ]
