# Generated by Django 4.1.1 on 2022-11-14 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0086_anteproyecto_estatusr1_anteproyecto_estatusr2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anteproyecto',
            name='estatusR1',
            field=models.CharField(blank=True, choices=[('PENDIENTE', 'PENDIENTE'), ('EN REVISION', 'EN REVISION'), ('ACEPTADO', 'ACEPTADO'), ('RECHAZADO', 'RECHAZADO')], default='PENDIENTE', max_length=15),
        ),
        migrations.AlterField(
            model_name='anteproyecto',
            name='estatusR2',
            field=models.CharField(blank=True, choices=[('PENDIENTE', 'PENDIENTE'), ('EN REVISION', 'EN REVISION'), ('ACEPTADO', 'ACEPTADO'), ('RECHAZADO', 'RECHAZADO')], default='PENDIENTE', max_length=15),
        ),
    ]
