# Generated by Django 4.1.1 on 2022-11-22 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0088_materia'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='materias',
            field=models.ManyToManyField(to='Accounts.materia'),
        ),
    ]
