# Generated by Django 4.1.1 on 2022-11-22 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0090_remove_docente_materias'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(blank=True, max_length=50, null=True)),
                ('materias', models.ManyToManyField(blank=True, null=True, to='Accounts.materia')),
            ],
        ),
        migrations.AddField(
            model_name='docente',
            name='perfilAcademico',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Accounts.perfilacademico'),
        ),
    ]
