# Generated by Django 4.1.1 on 2022-11-22 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0091_perfilacademico_docente_perfilacademico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilacademico',
            name='materias',
            field=models.ManyToManyField(blank=True, to='Accounts.materia'),
        ),
    ]
