# Generated by Django 4.1.1 on 2022-11-29 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0093_anteproyecto_materias'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Anteproyecto_materias',
            new_name='Anteproyecto_materia',
        ),
    ]
