# Generated by Django 4.1.1 on 2022-11-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0094_rename_anteproyecto_materias_anteproyecto_materia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observaciondocente',
            name='observacionD',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
